### ISSUE TITLE
can not read info.plist

### ISSUE THREAD

**Issue by alexsrs** [MaximAlien/Smile-Detector-CameraViewController#4]
how to solve this problem ? the demo not compile by a problem in .plist file

**Comment by MaximAlien** [comment]
What the compiler says you? I don't see any problems in Info.plist

**Comment by alexsrs** [comment]
error: could not read data from
'/Users/Creapix/Documents/Smile-Detector-CameraViewController-master/Demo/SmileCameraViewController/SmileCameraViewControllerTests/SmileCameraViewControllerTests-Info.plist':
The file “SmileCameraViewControllerTests-Info.plist” couldn’t be opened
because there is no such file.



2015-04-09 9:24 GMT-03:00 Maxim Makhun <notifications@github.com>:

**Comment by MaximAlien** [comment]
Sure? File is located in /Smile-Detector-CameraViewController/Demo/SmileCameraViewController/SmileCameraViewControllerTests/SmileCameraViewControllerDemoTests-Info.plist. Check using Finder or any other file manager.

**Comment by alexsrs** [comment]
yes file is located in /Smile-Detector-CameraViewController/Demo/
SmileCameraViewController/SmileCameraViewControllerTests/
SmileCameraViewControllerDemoTests-Info.plist.



2015-04-09 9:39 GMT-03:00 Maxim Makhun <notifications@github.com>:
